export default [
  'function accountValue(uint64 poolId, uint256 account) view returns (bool, uint128)',
  'function accounts(uint64, uint256) view returns (uint128 totalDebit, uint128 totalCredit, bool isDebitNormal, uint64 lastUpdated, bytes metadata)',
  // 'function addCredit(uint256 account, uint128 value)',
  // 'function addDebit(uint256 account, uint128 value)',
  // 'function addJournal((uint128 value, uint256 accountId)[] debits, (uint128 value, uint256 accountId)[] credits)',
  // 'function createAccount(uint64 poolId, uint256 account, bool isDebitNormal)',
  // 'function credited() view returns (uint128)',
  // 'function debited() view returns (uint128)',
  // 'function deny(address user)',
  'function exists(uint64 poolId, uint256 account) view returns (bool)',
  // 'function lock()',
  // 'function rely(address user)',
  // 'function setAccountMetadata(uint64 poolId, uint256 account, bytes metadata)',
  // 'function unlock(uint64 poolId)',
  // 'function wards(address) view returns (uint256)',
  // 'event CreateAccount(uint64 indexed poolId, uint256 indexed account, bool isDebitNormal)',
  // 'event Credit(uint64 indexed poolId, uint256 indexed account, uint128 value)',
  // 'event Debit(uint64 indexed poolId, uint256 indexed account, uint128 value)',
  // 'event Deny(address indexed user)',
  // 'event EndJournalId(uint64 indexed poolId, uint256 journalId)',
  // 'event Rely(address indexed user)',
  // 'event SetAccountMetadata(uint64 indexed poolId, uint256 indexed account, bytes metadata)',
  // 'event StartJournalId(uint64 indexed poolId, uint256 journalId)',
  // 'error AccountDoesNotExist()',
  // 'error AccountExists()',
  // 'error AccountingAlreadyUnlocked()',
  // 'error AccountingLocked()',
  // 'error NotAuthorized()',
  // 'error Unbalanced()',
] as const
