export default [
  'function AUTHORIZE_OPERATOR_TYPEHASH() view returns (bytes32)',
  'function DOMAIN_SEPARATOR() view returns (bytes32)',
  'function asset() view returns (address)',
  'function asyncManager() view returns (address)',
  'function asyncRedeemManager() view returns (address)',
  'function authorizations(address controller, bytes32 nonce) view returns (bool used)',
  'function authorizeOperator(address controller, address operator, bool approved, bytes32 nonce, uint256 deadline, bytes signature) returns (bool success)',
  'function baseManager() view returns (address)',
  'function cancelDepositRequest(uint256, address controller)',
  'function cancelRedeemRequest(uint256, address controller)',
  'function claimCancelDepositRequest(uint256, address receiver, address controller) returns (uint256 assets)',
  'function claimCancelRedeemRequest(uint256, address receiver, address controller) returns (uint256 shares)',
  'function claimableCancelDepositRequest(uint256, address controller) view returns (uint256 claimableAssets)',
  'function claimableCancelRedeemRequest(uint256, address controller) view returns (uint256 claimableShares)',
  'function claimableDepositRequest(uint256, address controller) view returns (uint256 claimableAssets)',
  'function claimableRedeemRequest(uint256, address controller) view returns (uint256 claimableShares)',
  'function convertToAssets(uint256 shares) view returns (uint256 assets)',
  'function convertToShares(uint256 assets) view returns (uint256 shares)',
  'function deny(address user)',
  'function deploymentChainId() view returns (uint256)',
  'function deposit(uint256 assets, address receiver, address controller) returns (uint256 shares)',
  'function deposit(uint256 assets, address receiver) returns (uint256 shares)',
  'function file(bytes32 what, address data)',
  'function invalidateNonce(bytes32 nonce)',
  'function isOperator(address, address) view returns (bool)',
  'function isPermissioned(address controller) view returns (bool)',
  'function maxDeposit(address controller) view returns (uint256 maxAssets)',
  'function maxMint(address controller) view returns (uint256 maxShares)',
  'function maxRedeem(address controller) view returns (uint256 maxShares)',
  'function maxWithdraw(address controller) view returns (uint256 maxAssets)',
  'function mint(uint256 shares, address receiver) returns (uint256 assets)',
  'function mint(uint256 shares, address receiver, address controller) returns (uint256 assets)',
  'function onCancelDepositClaimable(address controller, uint256 assets)',
  'function onCancelRedeemClaimable(address controller, uint256 shares)',
  'function onDepositClaimable(address controller, uint256 assets, uint256 shares)',
  'function onRedeemClaimable(address controller, uint256 assets, uint256 shares)',
  'function onRedeemRequest(address controller, address owner, uint256 shares)',
  'function pendingCancelDepositRequest(uint256, address controller) view returns (bool isPending)',
  'function pendingCancelRedeemRequest(uint256, address controller) view returns (bool isPending)',
  'function pendingDepositRequest(uint256, address controller) view returns (uint256 pendingAssets)',
  'function pendingRedeemRequest(uint256, address controller) view returns (uint256 pendingShares)',
  'function poolId() view returns (uint64)',
  'function previewDeposit(uint256) pure returns (uint256)',
  'function previewMint(uint256) pure returns (uint256)',
  'function previewRedeem(uint256) pure returns (uint256)',
  'function previewWithdraw(uint256) pure returns (uint256)',
  'function priceLastUpdated() view returns (uint64)',
  'function pricePerShare() view returns (uint256)',
  'function recoverTokens(address token, address receiver, uint256 amount)',
  'function recoverTokens(address token, uint256 tokenId, address receiver, uint256 amount)',
  'function redeem(uint256 shares, address receiver, address controller) returns (uint256 assets)',
  'function rely(address user)',
  'function requestDeposit(uint256 assets, address controller, address owner) returns (uint256)',
  'function requestRedeem(uint256 shares, address controller, address owner) returns (uint256)',
  'function root() view returns (address)',
  'function scId() view returns (bytes16)',
  'function setEndorsedOperator(address owner, bool approved)',
  'function setOperator(address operator, bool approved) returns (bool success)',
  'function share() view returns (address)',
  'function supportsInterface(bytes4 interfaceId) pure returns (bool)',
  'function totalAssets() view returns (uint256)',
  'function vaultKind() pure returns (uint8 vaultKind_)',
  'function wards(address) view returns (uint256)',
  'function withdraw(uint256 assets, address receiver, address controller) returns (uint256 shares)',
  'event CancelDepositClaim(address indexed controller, address indexed receiver, uint256 indexed requestId, address sender, uint256 assets)',
  'event CancelDepositClaimable(address indexed controller, uint256 indexed requestId, uint256 assets)',
  'event CancelDepositRequest(address indexed controller, uint256 indexed requestId, address sender)',
  'event CancelRedeemClaim(address indexed controller, address indexed receiver, uint256 indexed requestId, address sender, uint256 shares)',
  'event CancelRedeemClaimable(address indexed controller, uint256 indexed requestId, uint256 shares)',
  'event CancelRedeemRequest(address indexed controller, uint256 indexed requestId, address sender)',
  'event Deny(address indexed user)',
  'event Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)',
  'event DepositClaimable(address indexed controller, uint256 indexed requestId, uint256 assets, uint256 shares)',
  'event DepositRequest(address indexed controller, address indexed owner, uint256 indexed requestId, address sender, uint256 assets)',
  'event File(bytes32 indexed what, address data)',
  'event OperatorSet(address indexed controller, address indexed operator, bool approved)',
  'event RedeemClaimable(address indexed controller, uint256 indexed requestId, uint256 assets, uint256 shares)',
  'event RedeemRequest(address indexed controller, address indexed owner, uint256 indexed requestId, address sender, uint256 shares)',
  'event Rely(address indexed user)',
  'event Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)',
  'error AlreadyUsedAuthorization()',
  'error CannotSetSelfAsOperator()',
  'error ExpiredAuthorization()',
  'error FileUnrecognizedParam()',
  'error InsufficientBalance()',
  'error InvalidAuthorization()',
  'error InvalidController()',
  'error InvalidOwner()',
  'error InvalidSigner()',
  'error NoCode()',
  'error NotAuthorized()',
  'error NotEndorsed()',
  'error RequestDepositFailed()',
  'error RequestRedeemFailed()',
  'error SafeTransferEthFailed()',
  'error TransferFromFailed()',
  'error WrappedError(address target, bytes4 selector, bytes reason, bytes details)',
] as const
