export default [
  'function allowForceDepositCancel(uint64, bytes16, uint128, bytes32 investor) view returns (bool)',
  'function allowForceRedeemCancel(uint64, bytes16, uint128, bytes32 investor) view returns (bool)',
  'function approveDeposits(uint64 poolId, bytes16 scId_, uint128 depositAssetId, uint32 nowDepositEpochId, uint128 approvedAssetAmount, uint128 pricePoolPerAsset, address refund) payable',
  'function approveRedeems(uint64 poolId, bytes16 scId_, uint128 payoutAssetId, uint32 nowRedeemEpochId, uint128 approvedShareAmount, uint128 pricePoolPerAsset) payable',
  'function cancelDepositRequest(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 depositAssetId) returns (uint128 cancelledAssetAmount)',
  'function cancelRedeemRequest(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 payoutAssetId) returns (uint128 cancelledShareAmount)',
  'function deny(address user)',
  'function depositRequest(uint64, bytes16, uint128, bytes32 investor) view returns (uint128 pending, uint32 lastUpdate)',
  'function epochId(uint64, bytes16, uint128) view returns (uint32 deposit, uint32 issue, uint32 redeem, uint32 revoke)',
  'function epochInvestAmounts(uint64, bytes16, uint128, uint32 epochId_) view returns (uint128 approvedPoolAmount, uint128 approvedAssetAmount, uint128 pendingAssetAmount, uint128 pricePoolPerAsset, uint128 pricePoolPerShare, uint64 issuedAt)',
  'function epochRedeemAmounts(uint64, bytes16, uint128, uint32 epochId_) view returns (uint128 approvedShareAmount, uint128 pendingShareAmount, uint128 pricePoolPerAsset, uint128 pricePoolPerShare, uint128 payoutAssetAmount, uint64 revokedAt)',
  'function executeMulticall(bytes[] data) payable',
  'function file(bytes32 what, address data)',
  'function forceCancelDepositRequest(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 depositAssetId, address refund) payable',
  'function forceCancelRedeemRequest(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 payoutAssetId, address refund) payable',
  'function gateway() view returns (address)',
  'function hub() view returns (address)',
  'function hubRegistry() view returns (address)',
  'function issueShares(uint64 poolId, bytes16 scId_, uint128 depositAssetId, uint32 nowIssueEpochId, uint128 pricePoolPerShare, uint128 extraGasLimit, address refund) payable',
  'function maxDepositClaims(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 depositAssetId) view returns (uint32)',
  'function maxRedeemClaims(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 payoutAssetId) view returns (uint32)',
  'function multicall(bytes[] data) payable',
  'function notifyDeposit(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor, uint32 maxClaims, address refund) payable',
  'function notifyRedeem(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor, uint32 maxClaims, address refund) payable',
  'function nowDepositEpoch(uint64 poolId, bytes16 scId_, uint128 depositAssetId) view returns (uint32)',
  'function nowIssueEpoch(uint64 poolId, bytes16 scId_, uint128 depositAssetId) view returns (uint32)',
  'function nowRedeemEpoch(uint64 poolId, bytes16 scId_, uint128 depositAssetId) view returns (uint32)',
  'function nowRevokeEpoch(uint64 poolId, bytes16 scId_, uint128 depositAssetId) view returns (uint32)',
  'function pendingDeposit(uint64, bytes16, uint128) view returns (uint128)',
  'function pendingRedeem(uint64, bytes16, uint128) view returns (uint128)',
  'function queuedDepositRequest(uint64, bytes16, uint128, bytes32 investor) view returns (bool isCancelling, uint128 amount)',
  'function queuedRedeemRequest(uint64, bytes16, uint128, bytes32 investor) view returns (bool isCancelling, uint128 amount)',
  'function redeemRequest(uint64, bytes16, uint128, bytes32 investor) view returns (uint128 pending, uint32 lastUpdate)',
  'function rely(address user)',
  'function request(uint64 poolId, bytes16 scId, uint128 assetId, bytes payload)',
  'function requestDeposit(uint64 poolId, bytes16 scId_, uint128 amount, bytes32 investor, uint128 depositAssetId)',
  'function requestRedeem(uint64 poolId, bytes16 scId_, uint128 amount, bytes32 investor, uint128 payoutAssetId)',
  'function revokeShares(uint64 poolId, bytes16 scId_, uint128 payoutAssetId, uint32 nowRevokeEpochId, uint128 pricePoolPerShare, uint128 extraGasLimit, address refund) payable',
  'function supportsInterface(bytes4 interfaceId) pure returns (bool)',
  'function wards(address) view returns (uint256)',
  'event ApproveDeposits(uint64 indexed poolId, bytes16 indexed shareClassId, uint128 indexed assetId, uint32 epochId, uint128 approvedPoolAmount, uint128 approvedAssetAmount, uint128 pendingAssetAmount)',
  'event ApproveRedeems(uint64 indexed poolId, bytes16 indexed shareClassId, uint128 indexed assetId, uint32 epochId, uint128 approvedShareAmount, uint128 pendingShareAmount)',
  'event ClaimDeposit(uint64 indexed poolId, bytes16 indexed shareClassId, uint32 indexed epochId, bytes32 investor, uint128 assetId, uint128 paymentAssetAmount, uint128 pendingAssetAmount, uint128 payoutShareAmount, uint64 issuedAt)',
  'event ClaimRedeem(uint64 indexed poolId, bytes16 indexed shareClassId, uint32 indexed epochId, bytes32 investor, uint128 assetId, uint128 paymentShareAmount, uint128 pendingShareAmount, uint128 payoutAssetAmount, uint64 revokedAt)',
  'event Deny(address indexed user)',
  'event File(bytes32 what, address addr)',
  'event IssueShares(uint64 indexed poolId, bytes16 indexed shareClassId, uint128 indexed assetId, uint32 epochId, uint128 pricePoolPerShare, uint128 priceAssetPerShare, uint128 issuedShareAmount)',
  'event Rely(address indexed user)',
  'event RevokeShares(uint64 indexed poolId, bytes16 indexed shareClassId, uint128 indexed assetId, uint32 epochId, uint128 pricePoolPerShare, uint128 priceAssetPerShare, uint128 approvedShareAmount, uint128 payoutAssetAmount, uint128 payoutPoolAmount)',
  'event UpdateDepositRequest(uint64 indexed poolId, bytes16 indexed shareClassId, uint128 indexed assetId, uint32 epochId, bytes32 investor, uint128 pendingAmount, uint128 totalPendingAmount, uint128 queuedAmount, bool isQueuedCancellation)',
  'event UpdateRedeemRequest(uint64 indexed poolId, bytes16 indexed shareClassId, uint128 indexed assetId, uint32 epochId, bytes32 investor, uint128 pendingAmount, uint128 totalPendingAmount, uint128 queuedAmount, bool isQueuedCancellation)',
  'error CallFailedWithEmptyRevert()',
  'error CancellationInitializationRequired()',
  'error CancellationQueued()',
  'error DivisionByZero()',
  'error EpochNotFound()',
  'error EpochNotInSequence(uint32 epochId, uint32 actualEpochId)',
  'error FileUnrecognizedParam()',
  'error InsufficientPending()',
  'error IssuanceRequired()',
  'error MulDiv_Overflow()',
  'error NoOrderFound()',
  'error NotAuthorized()',
  'error RevocationRequired()',
  'error SliceOutOfBounds()',
  'error Uint128_Overflow()',
  'error Uint64_Overflow()',
  'error UnauthorizedSender()',
  'error UnknownRequestType()',
  'error UnknownRequestType()',
  'error ZeroApprovalAmount()',
] as const
