export default [
  // 'function BASE_COST() view returns (uint128)',
  // 'function cancelUpgrade() view returns (uint128)',
  // 'function executeTransferShares() view returns (uint128)',
  // 'function initiateTransferShares() view returns (uint128)',
  // 'function maxAssetPriceAge() view returns (uint128)',
  // 'function maxSharePriceAge() view returns (uint128)',
  'function maxBatchGasLimit(uint16 centrifugeId) view returns (uint128)',
  'function messageOverallGasLimit(uint16, bytes message) view returns (uint128)',
  // 'function notifyPool() view returns (uint128)',
  // 'function notifyPricePoolPerAsset() view returns (uint128)',
  // 'function notifyPricePoolPerShare() view returns (uint128)',
  // 'function notifyShareClass() view returns (uint128)',
  // 'function notifyShareMetadata() view returns (uint128)',
  // 'function recoverTokens() view returns (uint128)',
  // 'function registerAsset() view returns (uint128)',
  // 'function request() view returns (uint128)',
  // 'function requestCallback() view returns (uint128)',
  // 'function scheduleUpgrade() view returns (uint128)',
  // 'function setPoolAdapters() view returns (uint128)',
  // 'function setRequestManager() view returns (uint128)',
  // 'function trustedContractUpdate() view returns (uint128)',
  // 'function untrustedContractUpdate() view returns (uint128)',
  // 'function updateBalanceSheetManager() view returns (uint128)',
  // 'function updateGatewayManager() view returns (uint128)',
  // 'function updateHoldingAmount() view returns (uint128)',
  // 'function updateRestriction() view returns (uint128)',
  // 'function updateShareHook() view returns (uint128)',
  // 'function updateShares() view returns (uint128)',
  // 'function updateVaultDeployAndLink() view returns (uint128)',
  // 'function updateVaultLink() view returns (uint128)',
  // 'function updateVaultUnlink() view returns (uint128)',
  // 'error InvalidMessageType()',
  // 'error SliceOutOfBounds()',
  // 'error UnknownMessageType()',
] as const
