export default [
  'function accountId(uint64, bytes16, uint128, uint8 kind) view returns (uint256)',
  'function amount(uint64 poolId, bytes16 scId, uint128 assetId) view returns (uint128 amount_)',
  'function callOnSyncSnapshot(uint64 poolId, bytes16 scId, uint16 centrifugeId)',
  'function callOnTransferSnapshot(uint64 poolId, bytes16 scId, uint16 originCentrifugeId, uint16 targetCentrifugeId, uint128 amount_)',
  'function decrease(uint64 poolId, bytes16 scId, uint128 assetId, uint128 pricePoolPerAsset, uint128 amount_) returns (uint128 amountValue)',
  'function deny(address user)',
  'function holding(uint64, bytes16, uint128) view returns (uint128 assetAmount, uint128 assetAmountValue, address valuation, bool isLiability)',
  'function hubRegistry() view returns (address)',
  'function increase(uint64 poolId, bytes16 scId, uint128 assetId, uint128 pricePoolPerAsset, uint128 amount_) returns (uint128 amountValue)',
  'function initialize(uint64 poolId, bytes16 scId, uint128 assetId, address valuation_, bool isLiability_, (uint256 accountId, uint8 kind)[] accounts)',
  'function isInitialized(uint64 poolId, bytes16 scId, uint128 assetId) view returns (bool)',
  'function isLiability(uint64 poolId, bytes16 scId, uint128 assetId) view returns (bool)',
  'function rely(address user)',
  'function setAccountId(uint64 poolId, bytes16 scId, uint128 assetId, uint8 kind, uint256 accountId_)',
  'function setSnapshot(uint64 poolId, bytes16 scId, uint16 centrifugeId, bool isSnapshot, uint64 nonce)',
  'function setSnapshotHook(uint64 poolId, address hook)',
  'function snapshot(uint64, bytes16, uint16 centrifugeId) view returns (bool isSnapshot, uint64 nonce)',
  'function snapshotHook(uint64) view returns (address)',
  'function update(uint64 poolId, bytes16 scId, uint128 assetId) returns (bool isPositive, uint128 diffValue)',
  'function updateIsLiability(uint64 poolId, bytes16 scId, uint128 assetId, bool isLiability_)',
  'function updateValuation(uint64 poolId, bytes16 scId, uint128 assetId, address valuation_)',
  'function valuation(uint64 poolId, bytes16 scId, uint128 assetId) view returns (address)',
  'function value(uint64 poolId, bytes16 scId, uint128 assetId) view returns (uint128 value_)',
  'function wards(address) view returns (uint256)',
  'event Decrease(uint64 indexed, bytes16 indexed scId, uint128 indexed assetId, uint128 pricePoolPerAsset, uint128 amount, uint128 decreasedValue)',
  'event Deny(address indexed user)',
  'event Increase(uint64 indexed, bytes16 indexed scId, uint128 indexed assetId, uint128 pricePoolPerAsset, uint128 amount, uint128 increasedValue)',
  'event Initialize(uint64 indexed, bytes16 indexed scId, uint128 indexed assetId, address valuation, bool isLiability, (uint256 accountId, uint8 kind)[] accounts)',
  'event Rely(address indexed user)',
  'event SetAccountId(uint64 indexed poolId, bytes16 indexed scId, uint128 indexed assetId, uint8 kind, uint256 accountId)',
  'event SetSnapshot(uint64 indexed poolId, bytes16 indexed scId, uint16 indexed centrifugeId, bool isSnapshot, uint64 nonce)',
  'event SetSnapshotHook(uint64 indexed poolId, address hook)',
  'event Update(uint64 indexed poolId, bytes16 indexed scId, uint128 indexed assetId, bool isPositive, uint128 diffValue)',
  'event UpdateIsLiability(uint64 indexed poolId, bytes16 indexed scId, uint128 indexed assetId, bool isLiability)',
  'event UpdateValuation(uint64 indexed poolId, bytes16 indexed scId, uint128 indexed assetId, address valuation)',
  'error AlreadyInitialized()',
  'error HoldingNotFound()',
  'error HoldingNotZero()',
  'error InvalidNonce(uint64 expected, uint64 actual)',
  'error MulDiv_Overflow()',
  'error NotAuthorized()',
  'error Uint128_Overflow()',
  'error WrongAssetId()',
  'error WrongShareClassId()',
  'error WrongValuation()',
] as const
