export default [
  'function accounting() view returns (address)',
  'function addShareClass(uint64 poolId, string name, string symbol, bytes32 salt) returns (bytes16 scId)',
  'function createAccount(uint64 poolId, uint256 account, bool isDebitNormal) payable',
  'function createPool(uint64 poolId, address admin, uint128 currency) payable',
  'function deny(address user)',
  'function executeMulticall(bytes[] data) payable',
  'function feeHook() view returns (address)',
  'function file(bytes32 what, address data)',
  'function gateway() view returns (address)',
  'function holdingAccounts(uint256 assetAccount, uint256 equityAccount, uint256 gainAccount, uint256 lossAccount) pure returns ((uint256 accountId, uint8 kind)[])',
  'function holdings() view returns (address)',
  'function hubRegistry() view returns (address)',
  'function initializeHolding(uint64 poolId, bytes16 scId, uint128 assetId, address valuation, uint256 assetAccount, uint256 equityAccount, uint256 gainAccount, uint256 lossAccount) payable',
  'function initializeLiability(uint64 poolId, bytes16 scId, uint128 assetId, address valuation, uint256 expenseAccount, uint256 liabilityAccount) payable',
  'function liabilityAccounts(uint256 expenseAccount, uint256 liabilityAccount) pure returns ((uint256 accountId, uint8 kind)[])',
  'function multiAdapter() view returns (address)',
  'function multicall(bytes[] data) payable',
  'function notifyAssetPrice(uint64 poolId, bytes16 scId, uint128 assetId, address refund) payable',
  'function notifyPool(uint64 poolId, uint16 centrifugeId, address refund) payable',
  'function notifyShareClass(uint64 poolId, bytes16 scId, uint16 centrifugeId, bytes32 hook, address refund) payable',
  'function notifyShareMetadata(uint64 poolId, bytes16 scId, uint16 centrifugeId, address refund) payable',
  'function notifySharePrice(uint64 poolId, bytes16 scId, uint16 centrifugeId, address refund) payable',
  'function pricePoolPerAsset(uint64 poolId, bytes16 scId, uint128 assetId) view returns (uint128)',
  'function recoverTokens(address token, address receiver, uint256 amount)',
  'function recoverTokens(address token, uint256 tokenId, address receiver, uint256 amount)',
  'function rely(address user)',
  'function requestCallback(uint64 poolId, bytes16 scId, uint128 assetId, bytes payload, uint128 extraGasLimit, address refund) payable',
  'function sender() view returns (address)',
  'function setAccountMetadata(uint64 poolId, uint256 account, bytes metadata) payable',
  'function setAdapters(uint64 poolId, uint16 centrifugeId, address[] localAdapters, bytes32[] remoteAdapters, uint8 threshold, uint8 recoveryIndex, address refund) payable',
  'function setHoldingAccountId(uint64 poolId, bytes16 scId, uint128 assetId, uint8 kind, uint256 accountId) payable',
  'function setMaxAssetPriceAge(uint64 poolId, bytes16 scId, uint128 assetId, uint64 maxPriceAge, address refund) payable',
  'function setMaxSharePriceAge(uint64 poolId, bytes16 scId, uint16 centrifugeId, uint64 maxPriceAge, address refund) payable',
  'function setPoolMetadata(uint64 poolId, bytes metadata) payable',
  'function setRequestManager(uint64 poolId, uint16 centrifugeId, address hubManager, bytes32 spokeManager, address refund) payable',
  'function setSnapshotHook(uint64 poolId, address hook) payable',
  'function shareClassManager() view returns (address)',
  'function updateAccountingAmount(uint64 poolId, bytes16 scId, uint128 assetId, bool isPositive, uint128 diff) payable',
  'function updateAccountingValue(uint64 poolId, bytes16 scId, uint128 assetId, bool isPositive, uint128 diff) payable',
  'function updateBalanceSheetManager(uint64 poolId, uint16 centrifugeId, bytes32 who, bool canManage, address refund) payable',
  'function updateContract(uint64 poolId, bytes16 scId, uint16 centrifugeId, bytes32 target, bytes payload, uint128 extraGasLimit, address refund) payable',
  'function updateGatewayManager(uint64 poolId, uint16 centrifugeId, bytes32 who, bool canManage, address refund) payable',
  'function updateHoldingIsLiability(uint64 poolId, bytes16 scId, uint128 assetId, bool isLiability) payable',
  'function updateHoldingValuation(uint64 poolId, bytes16 scId, uint128 assetId, address valuation) payable',
  'function updateHoldingValue(uint64 poolId, bytes16 scId, uint128 assetId) payable',
  'function updateHubManager(uint64 poolId, address who, bool canManage) payable',
  'function updateJournal(uint64 poolId, (uint128 value, uint256 accountId)[] debits, (uint128 value, uint256 accountId)[] credits) payable',
  'function updateRestriction(uint64 poolId, bytes16 scId, uint16 centrifugeId, bytes payload, uint128 extraGasLimit, address refund) payable',
  'function updateShareClassMetadata(uint64 poolId, bytes16 scId, string name, string symbol) payable',
  'function updateShareHook(uint64 poolId, bytes16 scId, uint16 centrifugeId, bytes32 hook, address refund) payable',
  'function updateSharePrice(uint64 poolId, bytes16 scId, uint128 pricePoolPerShare, uint64 computedAt) payable',
  'function updateVault(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 vaultOrFactory, uint8 kind, uint128 extraGasLimit, address refund) payable',
  'function wards(address) view returns (uint256)',
  'event Deny(address indexed user)',
  'event File(bytes32 what, address addr)',
  'event ForwardTransferShares(uint16 indexed fromCentrifugeId, uint16 indexed toCentrifugeId, uint64 indexed poolId, bytes16 scId, bytes32 receiver, uint128 amount)',
  'event NotifyAssetPrice(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, uint128 assetId, uint128 pricePoolPerAsset)',
  'event NotifyPool(uint16 indexed centrifugeId, uint64 indexed poolId)',
  'event NotifyShareClass(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId)',
  'event NotifyShareMetadata(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, string name, string symbol)',
  'event NotifySharePrice(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, uint128 poolPerShare, uint64 computedAt)',
  'event Rely(address indexed user)',
  'event SetMaxAssetPriceAge(uint64 indexed poolId, bytes16 scId, uint128 assetId, uint64 maxPriceAge)',
  'event SetMaxSharePriceAge(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, uint64 maxPriceAge)',
  'event SetSpokeRequestManager(uint16 indexed centrifugeId, uint64 indexed poolId, bytes32 indexed manager)',
  'event UpdateBalanceSheetManager(uint16 indexed centrifugeId, uint64 indexed poolId, bytes32 indexed manager, bool canManage)',
  'event UpdateContract(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, bytes32 target, bytes payload)',
  'event UpdateRestriction(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, bytes payload)',
  'event UpdateShareHook(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, bytes32 hook)',
  'event UpdateVault(uint64 indexed poolId, bytes16 scId, uint128 assetId, bytes32 vaultOrFactory, uint8 kind)',
  'error AccountDoesNotExist()',
  'error AssetNotFound()',
  'error CallFailedWithEmptyRevert()',
  'error FileUnrecognizedParam()',
  'error InvalidAccountCombination()',
  'error InvalidPoolId()',
  'error InvalidRequestManager()',
  'error MulDiv_Overflow()',
  'error NoCode()',
  'error NotAuthorized()',
  'error NotManager()',
  'error PoolAlreadyUnlocked()',
  'error RequestManagerCallFailed()',
  'error SafeTransferEthFailed()',
  'error ShareClassNotFound()',
  'error Uint128_Overflow()',
  'error UnauthorizedSender()',
  'error WrappedError(address target, bytes4 selector, bytes reason, bytes details)',
] as const
