export default [
  // 'receive() external payable',
  // 'function contractUpdater() view returns (address)',
  'function execute((address decoder, address target, bytes targetData, uint256 value, bytes32[] proof)[] calls)',
  'function policy(address strategist) view returns (bytes32 root)',
  // 'function poolId() view returns (uint64)',
  // 'function trustedCall(uint64 poolId_, bytes16, bytes payload)',
  // 'event ExecuteCall(address indexed target, bytes4 indexed selector, bytes targetData, uint256 value)',
  // 'event UpdatePolicy(address indexed strategist, bytes32 oldRoot, bytes32 newRoot)',
  // 'error CallFailed()',
  // 'error DecodingFailed()',
  // 'error InsufficientBalance()',
  // 'error InvalidDecodersLength()',
  // 'error InvalidPoolId()',
  // 'error InvalidProof((address decoder, address target, bool valueNonZero, bytes4 selector, bytes addresses) leaf, bytes32[] proof)',
  // 'error InvalidProofLength()',
  // 'error InvalidTargetDataLength()',
  // 'error InvalidValuesLength()',
  // 'error NotAStrategist()',
  // 'error NotAuthorized()',
  // 'error PrefixNotZero()',
  // 'error WrappedError(address target, bytes4 selector, bytes reason, bytes details)',
] as const
