export default [
  // 'function balanceSheet() view returns (address)',
  // 'function contractUpdater() view returns (address)',
  // 'function deny(address user)',
  // 'function file(bytes32 what, address data)',
  // 'function gateway() view returns (address)',
  // 'function hubHandler() view returns (address)',
  'function localCentrifugeId() view returns (uint16)',
  // 'function multiAdapter() view returns (address)',
  // 'function rely(address user)',
  // 'function scheduleAuth() view returns (address)',
  // 'function sendCancelUpgrade(uint16 centrifugeId, bytes32 target, address refund) payable',
  // 'function sendExecuteTransferShares(uint16 targetCentrifugeId, uint64 poolId, bytes16 scId, bytes32 receiver, uint128 amount, uint128 extraGasLimit, address refund) payable',
  // 'function sendInitiateTransferShares(uint16 targetCentrifugeId, uint64 poolId, bytes16 scId, bytes32 receiver, uint128 amount, uint128 extraGasLimit, uint128 remoteExtraGasLimit, address refund) payable',
  // 'function sendNotifyPool(uint16 centrifugeId, uint64 poolId, address refund) payable',
  // 'function sendNotifyPricePoolPerAsset(uint64 poolId, bytes16 scId, uint128 assetId, uint128 pricePoolPerAsset, address refund) payable',
  // 'function sendNotifyPricePoolPerShare(uint16 chainId, uint64 poolId, bytes16 scId, uint128 pricePoolPerShare, uint64 computedAt, address refund) payable',
  // 'function sendNotifyShareClass(uint16 centrifugeId, uint64 poolId, bytes16 scId, string name, string symbol, uint8 decimals, bytes32 salt, bytes32 hook, address refund) payable',
  // 'function sendNotifyShareMetadata(uint16 centrifugeId, uint64 poolId, bytes16 scId, string name, string symbol, address refund) payable',
  // 'function sendRecoverTokens(uint16 centrifugeId, bytes32 target, bytes32 token, uint256 tokenId, bytes32 to, uint256 amount, address refund) payable',
  // 'function sendRegisterAsset(uint16 centrifugeId, uint128 assetId, uint8 decimals, address refund) payable',
  // 'function sendRequest(uint64 poolId, bytes16 scId, uint128 assetId, bytes payload, address refund) payable',
  // 'function sendRequestCallback(uint64 poolId, bytes16 scId, uint128 assetId, bytes payload, uint128 extraGasLimit, address refund) payable',
  // 'function sendScheduleUpgrade(uint16 centrifugeId, bytes32 target, address refund) payable',
  // 'function sendSetMaxAssetPriceAge(uint64 poolId, bytes16 scId, uint128 assetId, uint64 maxPriceAge, address refund) payable',
  // 'function sendSetMaxSharePriceAge(uint16 centrifugeId, uint64 poolId, bytes16 scId, uint64 maxPriceAge, address refund) payable',
  // 'function sendSetPoolAdapters(uint16 centrifugeId, uint64 poolId, bytes32[] adapters, uint8 threshold, uint8 recoveryIndex, address refund) payable',
  // 'function sendSetRequestManager(uint16 centrifugeId, uint64 poolId, bytes32 manager, address refund) payable',
  // 'function sendTrustedContractUpdate(uint16 centrifugeId, uint64 poolId, bytes16 scId, bytes32 target, bytes payload, uint128 extraGasLimit, address refund) payable',
  // 'function sendUntrustedContractUpdate(uint64 poolId, bytes16 scId, bytes32 target, bytes payload, bytes32 sender, uint128 extraGasLimit, address refund) payable',
  // 'function sendUpdateBalanceSheetManager(uint16 centrifugeId, uint64 poolId, bytes32 who, bool canManage, address refund) payable',
  // 'function sendUpdateGatewayManager(uint16 centrifugeId, uint64 poolId, bytes32 who, bool canManage, address refund) payable',
  // 'function sendUpdateHoldingAmount(uint64 poolId, bytes16 scId, uint128 assetId, (uint128 netAmount, bool isIncrease, bool isSnapshot, uint64 nonce) data, uint128 pricePoolPerAsset, uint128 extraGasLimit, address refund) payable',
  // 'function sendUpdateRestriction(uint16 centrifugeId, uint64 poolId, bytes16 scId, bytes payload, uint128 extraGasLimit, address refund) payable',
  // 'function sendUpdateShareHook(uint16 centrifugeId, uint64 poolId, bytes16 scId, bytes32 hook, address refund) payable',
  // 'function sendUpdateShares(uint64 poolId, bytes16 scId, (uint128 netAmount, bool isIncrease, bool isSnapshot, uint64 nonce) data, uint128 extraGasLimit, address refund) payable',
  // 'function sendUpdateVault(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 vaultOrFactory, uint8 kind, uint128 extraGasLimit, address refund) payable',
  // 'function spoke() view returns (address)',
  // 'function tokenRecoverer() view returns (address)',
  // 'function vaultRegistry() view returns (address)',
  // 'function wards(address) view returns (uint256)',
  // 'event Deny(address indexed user)',
  // 'event File(bytes32 indexed what, address addr)',
  // 'event Rely(address indexed user)',
  // 'error CannotBeSentLocally()',
  // 'error CannotRefund()',
  // 'error FileUnrecognizedParam()',
  // 'error NotAuthorized()',
  // 'error PrefixNotZero()',
  // 'error SliceOutOfBounds()',
  // 'error SliceOverflow()',
  // 'error Uint16_Overflow()',
  // 'error Uint64_Overflow()',
] as const
