export default [
  // 'function GLOBAL_POOL() view returns (uint64)',
  // 'function activeSessionId(uint16 centrifugeId, uint64 poolId) view returns (uint64)',
  'function adapters(uint16 centrifugeId, uint64, uint256) view returns (address)',
  // 'function deny(address user)',
  'function estimate(uint16 centrifugeId, bytes payload, uint256 gasLimit) view returns (uint256 total)',
  // 'function file(bytes32 what, address instance)',
  // 'function gateway() view returns (address)',
  // 'function handle(uint16 centrifugeId, bytes payload)',
  // 'function inbound(uint16 centrifugeId, bytes32 payloadHash) view returns (uint64 sessionId)',
  // 'function localCentrifugeId() view returns (uint16)',
  // 'function messageProperties() view returns (address)',
  'function quorum(uint16 centrifugeId, uint64 poolId) view returns (uint8)',
  // 'function recoveryIndex(uint16 centrifugeId, uint64 poolId) view returns (uint8)',
  // 'function rely(address user)',
  // 'function send(uint16 centrifugeId, bytes payload, uint256 gasLimit, address refund) payable returns (bytes32)',
  // 'function setAdapters(uint16 centrifugeId, uint64 poolId, address[] addresses, uint8 threshold_, uint8 recoveryIndex_)',
  'function threshold(uint16 centrifugeId, uint64 poolId) view returns (uint8)',
  // 'function votes(uint16 centrifugeId, bytes32 payloadHash) view returns (int16[8])',
  // 'function wards(address) view returns (uint256)',
  // 'event Deny(address indexed user)',
  // 'event File(bytes32 indexed what, address addr)',
  // 'event HandlePayload(uint16 indexed centrifugeId, bytes32 indexed payloadId, bytes payload, address adapter)',
  // 'event Rely(address indexed user)',
  // 'event SendPayload(uint16 indexed centrifugeId, bytes32 indexed payloadId, bytes payload, address adapter, bytes32 adapterData, uint256 gasLimit, uint256 gasPaid, address refund)',
  // 'event SetAdapters(uint16 centrifugeId, uint64 poolId, address[] adapters, uint8 threshold, uint8 recoveryIndex)',
  // 'error EmptyAdapterSet()',
  // 'error ExceedsMax()',
  // 'error FileUnrecognizedParam()',
  // 'error InvalidAdapter()',
  // 'error NoDuplicatesAllowed()',
  // 'error NotAuthorized()',
  // 'error NotEntrypoint()',
  // 'error RecoveryIndexHigherThanQuorum()',
  // 'error ThresholdHigherThanQuorum()',
  // 'error Uint8_Overflow()',
  // 'error UnknownChainId()',
] as const
