export default [
  'function accounting() view returns (address)',
  'function assetAccount(uint128 assetId) pure returns (uint256)',
  'function closeGainLoss(uint64 poolId, uint16 centrifugeId)',
  'function equityAccount(uint16 centrifugeId) pure returns (uint256)',
  'function expenseAccount(uint128 assetId) pure returns (uint256)',
  'function gainAccount(uint16 centrifugeId) pure returns (uint256)',
  'function holdings() view returns (address)',
  'function hub() view returns (address)',
  'function hubRegistry() view returns (address)',
  'function initializeHolding(uint64 poolId, bytes16 scId, uint128 assetId, address valuation)',
  'function initializeLiability(uint64 poolId, bytes16 scId, uint128 assetId, address valuation)',
  'function initializeNetwork(uint64 poolId, uint16 centrifugeId)',
  'function initialized(uint64, uint16 centrifugeId) view returns (bool)',
  'function liabilityAccount(uint16 centrifugeId) pure returns (uint256)',
  'function lossAccount(uint16 centrifugeId) pure returns (uint256)',
  'function manager(uint64, address) view returns (bool)',
  'function navHook(uint64) view returns (address)',
  'function netAssetValue(uint64 poolId, uint16 centrifugeId) view returns (uint128)',
  'function onSync(uint64 poolId, bytes16 scId, uint16 centrifugeId)',
  'function onTransfer(uint64 poolId, bytes16 scId, uint16 fromCentrifugeId, uint16 toCentrifugeId, uint128 sharesTransferred)',
  'function setNAVHook(uint64 poolId, address navHook_)',
  'function updateHoldingValuation(uint64 poolId, bytes16 scId, uint128 assetId, address valuation)',
  'function updateHoldingValue(uint64 poolId, bytes16 scId, uint128 assetId)',
  'function updateManager(uint64 poolId, address manager_, bool canManage)',
  'event InitializeHolding(uint64 indexed poolId, bytes16 indexed scId, uint128 indexed assetId)',
  'event InitializeLiability(uint64 indexed poolId, bytes16 indexed scId, uint128 indexed assetId)',
  'event InitializeNetwork(uint64 indexed poolId, uint16 indexed centrifugeId)',
  'event SetNavHook(uint64 indexed poolId, address indexed navHook)',
  'event Sync(uint64 indexed poolId, bytes16 indexed scId, uint16 indexed centrifugeId, uint128 netAssetValue)',
  'event Transfer(uint64 indexed poolId, bytes16 scId, uint16 indexed fromCentrifugeId, uint16 indexed toCentrifugeId, uint128 sharesTransferred)',
  'event UpdateManager(uint64 indexed poolId, address indexed manager, bool canManage)',
  'error AlreadyInitialized()',
  'error ExceedsMaxAccounts()',
  'error InvalidNAVHook()',
  'error InvalidStateOfAccounts()',
  'error MismatchedEpochs()',
  'error NotAuthorized()',
  'error NotInitialized()',
] as const
