export default [
  // 'function balanceSheet() view returns (address)',
  // 'function contractUpdater() view returns (address)',
  'function deposit(address asset, uint256, uint128 amount, address)',
  'function offramp(address asset, address receiver) view returns (bool isEnabled)',
  'function onramp(address asset) view returns (bool)',
  // 'function poolId() v?iew returns (uint64)',
  'function relayer(address relayer) view returns (bool)',
  // 'function scId() view returns (bytes16)',
  // 'function supportsInterface(bytes4 interfaceId) pure returns (bool)',
  // 'function trustedCall(uint64 poolId_, bytes16 scId_, bytes payload)',
  'function withdraw(address asset, uint256, uint128 amount, address receiver)',
  'event UpdateOfframp(address indexed asset, address receiver, bool isEnabled)',
  'event UpdateOnramp(address indexed asset, bool isEnabled)',
  'event UpdateRelayer(address indexed relayer, bool isEnabled)',
  // 'error ERC6909NotSupported()',
  // 'error InvalidAmount()',
  // 'error InvalidOfframpDestination()',
  // 'error InvalidPoolId()',
  // 'error InvalidShareClassId()',
  // 'error NoCode()',
  // 'error NotAllowedOnrampAsset()',
  // 'error NotContractUpdater()',
  // 'error NotRelayer()',
  // 'error PrefixNotZero()',
  // 'error UnknownTrustedCall()',
  // 'error WrappedError(address target, bytes4 selector, bytes reason, bytes details)',
] as const
