export default [
  // 'function balanceSheet() view returns (address)',
  // 'function deny(address user)',
  'function escrow(uint64 poolId) view returns (address)',
  // 'function file(bytes32 what, address data)',
  // 'function gateway() view returns (address)',
  // 'function newEscrow(uint64 poolId) returns (address)',
  // 'function rely(address user)',
  // 'function root() view returns (address)',
  // 'function wards(address) view returns (uint256)',
  // 'event Deny(address indexed user)',
  // 'event DeployPoolEscrow(uint64 indexed poolId, address indexed escrow)',
  // 'event File(bytes32 what, address data)',
  // 'event Rely(address indexed user)',
  // 'error EscrowAlreadyDeployed()',
  // 'error FileUnrecognizedParam()',
  // 'error NotAuthorized()',
] as const
