export default [
  // 'function balanceSheet() view returns (address)',
  // 'function contractUpdater() view returns (address)',
  // 'function deny(address user)',
  // 'function gateway() view returns (address)',
  // 'function rely(address user)',
  // 'function scQueueState(uint64, bytes16) view returns (uint64 minDelay, uint64 lastSync, uint128 extraGasLimit)',
  'function sync(uint64 poolId, bytes16 scId, uint128[] assetIds, address refund) payable',
  // 'function syncCallback(uint64 poolId, bytes16 scId, uint128[] assetIds)',
  // 'function trustedCall(uint64 poolId, bytes16 scId, bytes payload)',
  // 'function wards(address) view returns (uint256)',
  // 'event Deny(address indexed user)',
  // 'event Rely(address indexed user)',
  // 'event UpdateQueueConfig(uint64 indexed poolId, bytes16 indexed scId, uint64 newMinDelay, uint128 newExtraGasLimit)',
  // 'error InsufficientFunds()',
  // 'error MinDelayNotElapsed()',
  // 'error NoUpdateForAsset()',
  // 'error NotAuthorized()',
  // 'error NotContractUpdater()',
] as const
