export default [
  'function addShareClass(uint64 poolId, string name, string symbol, bytes32 salt) returns (bytes16 scId_)',
  'function deny(address user)',
  'function exists(uint64 poolId, bytes16 scId_) view returns (bool)',
  'function hubRegistry() view returns (address)',
  'function issuance(uint64, bytes16, uint16 centrifugeId) view returns (uint128)',
  'function metadata(uint64, bytes16) view returns (string name, string symbol, bytes32 salt)',
  'function previewNextShareClassId(uint64 poolId) view returns (bytes16 scId)',
  'function previewShareClassId(uint64 poolId, uint32 index) pure returns (bytes16 scId)',
  'function pricePoolPerShare(uint64, bytes16) view returns (uint128 price, uint64 computedAt)',
  'function rely(address user)',
  'function salts(bytes32 salt) view returns (bool)',
  'function shareClassCount(uint64) view returns (uint32)',
  'function shareClassIds(uint64, bytes16) view returns (bool)',
  'function totalIssuance(uint64, bytes16) view returns (uint128)',
  'function updateMetadata(uint64 poolId, bytes16 scId_, string name, string symbol)',
  'function updateSharePrice(uint64 poolId, bytes16 scId_, uint128 pricePoolPerShare_, uint64 computedAt)',
  'function updateShares(uint16 centrifugeId, uint64 poolId, bytes16 scId_, uint128 amount, bool isIssuance)',
  'function wards(address) view returns (uint256)',
  'event AddShareClass(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed index, string name, string symbol, bytes32 salt)',
  'event Deny(address indexed user)',
  'event Rely(address indexed user)',
  'event RemoteIssueShares(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 indexed scId, uint128 amount)',
  'event RemoteRevokeShares(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 indexed scId, uint128 amount)',
  'event UpdateMetadata(uint64 indexed poolId, bytes16 indexed scId, string name, string symbol)',
  'event UpdatePricePoolPerShare(uint64 indexed poolId, bytes16 indexed scId, uint128 price, uint64 computedAt)',
  'error AlreadyUsedSalt()',
  'error CannotSetFuturePrice()',
  'error DecreaseMoreThanIssued()',
  'error InvalidMetadataName()',
  'error InvalidMetadataSize()',
  'error InvalidMetadataSymbol()',
  'error InvalidSalt()',
  'error NotAuthorized()',
  'error PoolMissing()',
  'error ShareClassNotFound()',
] as const
