export default [
  'function addPool(uint64 poolId)',
  'function addShareClass(uint64 poolId, bytes16 scId, string name, string symbol, uint8 decimals, bytes32 salt, address hook)',
  'function assetToId(address asset, uint256 tokenId) view returns (uint128 assetId)',
  'function crosschainTransferShares(uint16 centrifugeId, uint64 poolId, bytes16 scId, bytes32 receiver, uint128 amount, uint128 remoteExtraGasLimit) payable',
  'function crosschainTransferShares(uint16 centrifugeId, uint64 poolId, bytes16 scId, bytes32 receiver, uint128 amount, uint128 extraGasLimit, uint128 remoteExtraGasLimit, address refund) payable',
  'function deny(address user)',
  'function executeTransferShares(uint64 poolId, bytes16 scId, bytes32 receiver, uint128 amount)',
  'function file(bytes32 what, address data)',
  'function gateway() view returns (address)',
  'function idToAsset(uint128 assetId) view returns (address asset, uint256 tokenId)',
  'function isPoolActive(uint64 poolId) view returns (bool)',
  'function linkToken(uint64 poolId, bytes16 scId, address shareToken_)',
  'function markersPricePoolPerAsset(uint64 poolId, bytes16 scId, uint128 assetId) view returns (uint64 computedAt, uint64 maxAge, uint64 validUntil)',
  'function markersPricePoolPerShare(uint64 poolId, bytes16 scId) view returns (uint64 computedAt, uint64 maxAge, uint64 validUntil)',
  'function pool(uint64) view returns (uint64 createdAt)',
  'function poolEscrowFactory() view returns (address)',
  'function pricePoolPerAsset(uint64 poolId, bytes16 scId, uint128 assetId, bool checkValidity) view returns (uint128 price)',
  'function pricePoolPerShare(uint64 poolId, bytes16 scId, bool checkValidity) view returns (uint128 price)',
  'function pricesPoolPer(uint64 poolId, bytes16 scId, uint128 assetId, bool checkValidity) view returns (uint128 pricePoolPerAsset_, uint128 pricePoolPerShare_)',
  'function recoverTokens(address token, address receiver, uint256 amount)',
  'function recoverTokens(address token, uint256 tokenId, address receiver, uint256 amount)',
  'function registerAsset(uint16 centrifugeId, address asset, uint256 tokenId, address refund) payable returns (uint128 assetId)',
  'function rely(address user)',
  'function request(uint64 poolId, bytes16 scId, uint128 assetId, bytes payload, address refund, bool unpaid) payable',
  'function requestCallback(uint64 poolId, bytes16 scId, uint128 assetId, bytes payload)',
  'function requestManager(uint64) view returns (address)',
  'function sender() view returns (address)',
  'function setMaxAssetPriceAge(uint64 poolId, bytes16 scId, uint128 assetId, uint64 maxPriceAge)',
  'function setMaxSharePriceAge(uint64 poolId, bytes16 scId, uint64 maxPriceAge)',
  'function setRequestManager(uint64 poolId, address manager)',
  'function setShareTokenVault(uint64 poolId, bytes16 scId, address asset, address vault)',
  'function shareClass(uint64, bytes16) view returns (address shareToken, (uint128 price, uint64 computedAt, uint64 maxAge) pricePoolPerShare)',
  'function shareToken(uint64 poolId, bytes16 scId) view returns (address)',
  'function tokenFactory() view returns (address)',
  'function updateContract(uint64 poolId, bytes16 scId, bytes32 target, bytes payload, uint128 extraGasLimit, address refund) payable',
  'function updatePricePoolPerAsset(uint64 poolId, bytes16 scId, uint128 assetId, uint128 price, uint64 computedAt)',
  'function updatePricePoolPerShare(uint64 poolId, bytes16 scId, uint128 price, uint64 computedAt)',
  'function updateRestriction(uint64 poolId, bytes16 scId, bytes update)',
  'function updateShareHook(uint64 poolId, bytes16 scId, address hook)',
  'function updateShareMetadata(uint64 poolId, bytes16 scId, string name, string symbol)',
  'function wards(address) view returns (uint256)',
  'event AddPool(uint64 indexed poolId)',
  'event AddShareClass(uint64 indexed poolId, bytes16 indexed scId, address token)',
  'event Deny(address indexed user)',
  'event DeployVault(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, address factory, address vault, uint8 kind)',
  'event ExecuteTransferShares(uint64 indexed poolId, bytes16 indexed scId, address indexed receiver, uint128 amount)',
  'event File(bytes32 indexed what, address data)',
  'event InitiateTransferShares(uint16 centrifugeId, uint64 indexed poolId, bytes16 indexed scId, address indexed sender, bytes32 destinationAddress, uint128 amount)',
  'event LinkVault(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, address vault)',
  'event RegisterAsset(uint16 centrifugeId, uint128 indexed assetId, address indexed asset, uint256 indexed tokenId, string name, string symbol, uint8 decimals, bool isInitialization)',
  'event Rely(address indexed user)',
  'event SetRequestManager(uint64 indexed poolId, address manager)',
  'event UnlinkVault(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, address vault)',
  'event UntrustedContractUpdate(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, bytes32 target, bytes payload, address indexed sender)',
  'event UpdateAssetPrice(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, uint128 price, uint64 computedAt)',
  'event UpdateMaxAssetPriceAge(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, uint64 maxPriceAge)',
  'event UpdateMaxSharePriceAge(uint64 indexed poolId, bytes16 indexed scId, uint64 maxPriceAge)',
  'event UpdateSharePrice(uint64 indexed poolId, bytes16 indexed scId, uint128 price, uint64 computedAt)',
  'error AlreadyLinkedVault()',
  'error AlreadyUnlinkedVault()',
  'error AssetMissingDecimals()',
  'error CannotSetOlderPrice()',
  'error CrossChainTransferNotAllowed()',
  'error FileUnrecognizedParam()',
  'error InvalidFactory()',
  'error InvalidHook()',
  'error InvalidManager()',
  'error InvalidPool()',
  'error InvalidPrice()',
  'error InvalidRequestManager()',
  'error InvalidVault()',
  'error LocalTransferNotAllowed()',
  'error MalformedVaultUpdateMessage()',
  'error NoCode()',
  'error NotAuthorized()',
  'error OldHook()',
  'error OldMetadata()',
  'error PoolAlreadyAdded()',
  'error PrefixNotZero()',
  'error RequestManagerNotSet()',
  'error SafeTransferEthFailed()',
  'error ShareClassAlreadyRegistered()',
  'error ShareTokenDoesNotExist()',
  'error ShareTokenTransferFailed()',
  'error TooFewDecimals()',
  'error TooManyDecimals()',
  'error TransferFromFailed()',
  'error UnauthorizedSender()',
  'error UnknownAsset()',
  'error UnknownVault()',
  'error WrappedError(address target, bytes4 selector, bytes reason, bytes details)',
] as const
