export default [
  'function balanceSheet() view returns (address)',
  'function convertToAssets(address vault_, uint256 shares) view returns (uint256 assets)',
  'function convertToShares(address vault_, uint256 assets) view returns (uint256 shares)',
  'function deny(address user)',
  'function deposit(address vault_, uint256 assets, address receiver, address owner) returns (uint256 shares)',
  'function file(bytes32 what, address data)',
  'function maxDeposit(address vault_, address owner) view returns (uint256 assets)',
  'function maxMint(address vault_, address owner) view returns (uint256 shares)',
  'function maxReserve(uint64, bytes16, address asset, uint256 tokenId) view returns (uint128)',
  'function mint(address vault_, uint256 shares, address receiver, address owner) returns (uint256 assets)',
  'function previewDeposit(address vault_, address, uint256 assets) view returns (uint256 shares)',
  'function previewMint(address vault_, address, uint256 shares) view returns (uint256 assets)',
  'function pricePoolPerShare(uint64 poolId, bytes16 scId) view returns (uint128 price)',
  'function recoverTokens(address token, address receiver, uint256 amount)',
  'function recoverTokens(address token, uint256 tokenId, address receiver, uint256 amount)',
  'function rely(address user)',
  'function setMaxReserve(uint64 poolId, bytes16 scId, address asset, uint256 tokenId, uint128 maxReserve_)',
  'function setValuation(uint64 poolId, bytes16 scId, address valuation_)',
  'function spoke() view returns (address)',
  'function trustedCall(uint64 poolId, bytes16 scId, bytes payload)',
  'function valuation(uint64, bytes16) view returns (address)',
  'function vaultRegistry() view returns (address)',
  'function wards(address) view returns (uint256)',
  'event Deny(address indexed user)',
  'event File(bytes32 indexed what, address data)',
  'event Rely(address indexed user)',
  'event SetMaxReserve(uint64 indexed poolId, bytes16 indexed scId, address asset, uint256 tokenId, uint128 maxReserve)',
  'event SetValuation(uint64 indexed poolId, bytes16 indexed scId, address valuation)',
  'error DivisionByZero()',
  'error ExceedsMaxDeposit()',
  'error ExceedsMaxMint()',
  'error FileUnrecognizedParam()',
  'error MulDiv_Overflow()',
  'error NoCode()',
  'error NotAuthorized()',
  'error PrefixNotZero()',
  'error SafeTransferEthFailed()',
  'error SecondaryManagerDoesNotExist()',
  'error ShareTokenDoesNotExist()',
  'error Uint128_Overflow()',
  'error UnknownTrustedCall()',
  'error WrappedError(address target, bytes4 selector, bytes reason, bytes details)',
] as const
