export default [
  // 'function deny(address user)',
  // 'function deployVault(uint64 poolId, bytes16 scId, uint128 assetId, address factory) returns (address)',
  // 'function file(bytes32 what, address data)',
  'function isLinked(address vault_) view returns (bool)',
  // 'function linkVault(uint64 poolId, bytes16 scId, uint128 assetId, address vault_)',
  // 'function recoverTokens(address token, address receiver, uint256 amount)',
  // 'function recoverTokens(address token, uint256 tokenId, address receiver, uint256 amount)',
  // 'function registerVault(uint64 poolId, bytes16 scId, uint128 assetId, address asset, uint256 tokenId, address factory, address vault_)',
  // 'function rely(addre?ss user)',
  // 'function spoke() view returns (address)',
  // 'function unlinkVault(uint64 poolId, bytes16 scId, uint128 assetId, address vault_)',
  // 'function updateVault(uint64 poolId, bytes16 scId, uint128 assetId, address vaultOrFactory, uint8 kind)',
  'function vault(uint64, bytes16, uint128, address) view returns (address)',
  'function vaultDetails(address vault_) view returns ((uint128 assetId, address asset, uint256 tokenId, bool isLinked) details)',
  // 'function wards(address) view returns (uint256)',
  // 'event Deny(address indexed user)',
  'event DeployVault(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, address factory, address vault, uint8 kind)',
  // 'event File(bytes32 indexed what, address data)',
  'event LinkVault(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, address vault)',
  // 'event Rely(address indexed user)',
  'event UnlinkVault(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, address vault)',
  // 'error AlreadyLinkedVault()',
  // 'error AlreadyUnlinkedVault()',
  // 'error FileUnrecognizedParam()',
  // 'error InvalidRequestManager()',
  // 'error InvalidVault()',
  // 'error MalformedVaultUpdateMessage()',
  // 'error NoCode()',
  // 'error NotAuthorized()',
  // 'error SafeTransferEthFailed()',
  // 'error UnknownVault()',
  // 'error WrappedError(address target, bytes4 selector, bytes reason, bytes details)',
] as const
