export default [
  'function cancelDepositRequest(address vault) payable',
  'function cancelRedeemRequest(address vault) payable',
  'function claimCancelDepositRequest(address vault, address receiver, address controller) payable',
  'function claimCancelRedeemRequest(address vault, address receiver, address controller) payable',
  'function claimDeposit(address vault, address receiver, address controller) payable',
  'function claimRedeem(address vault, address receiver, address controller) payable',
  'function crosschainTransferShares(address vault, uint128 shares, uint16 centrifugeId, bytes32 receiver, address owner, uint128 extraGasLimit, uint128 remoteExtraGasLimit, address refund) payable',
  'function deny(address user)',
  'function deposit(address vault, uint256 assets, address receiver, address owner) payable',
  'function disable(address vault) payable',
  'function enable(address vault) payable',
  'function enableLockDepositRequest(address vault, uint256 amount) payable',
  'function escrow() view returns (address)',
  'function executeLockedDepositRequest(address vault, address controller) payable',
  'function executeMulticall(bytes[] data) payable',
  'function gateway() view returns (address)',
  'function getVault(uint64 poolId, bytes16 scId, address asset) view returns (address)',
  'function hasPermissions(address vault, address controller) view returns (bool)',
  'function isEnabled(address vault, address controller) view returns (bool)',
  'function lockDepositRequest(address vault, uint256 amount, address controller, address owner) payable',
  'function lockedRequests(address controller, address vault) view returns (uint256 amount)',
  'function multicall(bytes[] data) payable',
  'function permit(address asset, address spender, uint256 assets, uint256 deadline, uint8 v, bytes32 r, bytes32 s) payable',
  'function recoverTokens(address token, address receiver, uint256 amount)',
  'function recoverTokens(address token, uint256 tokenId, address receiver, uint256 amount)',
  'function rely(address user)',
  'function requestDeposit(address vault, uint256 amount, address controller, address owner) payable',
  'function requestRedeem(address vault, uint256 amount, address controller, address owner) payable',
  'function spoke() view returns (address)',
  'function unlockDepositRequest(address vault, address receiver) payable',
  'function vaultRegistry() view returns (address)',
  'function wards(address) view returns (uint256)',
  'event Deny(address indexed user)',
  'event ExecuteLockedDepositRequest(address indexed vault, address indexed controller, address sender)',
  'event LockDepositRequest(address indexed vault, address indexed controller, address indexed owner, address sender, uint256 amount)',
  'event Rely(address indexed user)',
  'event UnlockDepositRequest(address indexed vault, address indexed controller, address indexed receiver)',
  'error CallFailedWithEmptyRevert()',
  'error InvalidOwner()',
  'error InvalidSender()',
  'error NoCode()',
  'error NoLockedBalance()',
  'error NoLockedRequest()',
  'error NonAsyncVault()',
  'error NonSyncDepositVault()',
  'error NotAuthorized()',
  'error SafeTransferEthFailed()',
  'error UnauthorizedSender()',
  'error WrappedError(address target, bytes4 selector, bytes reason, bytes details)',
  'error ZeroBalance()',
] as const
