import { Abi } from "viem";

export const GrooveBasinAbi = [
  {
    inputs: [
      { internalType: "address", name: "owner_", type: "address" },
      { internalType: "address", name: "liquidityProvider_", type: "address" },
      { internalType: "address", name: "swapToken_", type: "address" },
      { internalType: "address", name: "collateralToken_", type: "address" },
      { internalType: "address", name: "creditToken_", type: "address" },
      { internalType: "address", name: "swapTokenRateProvider_", type: "address" },
      { internalType: "address", name: "collateralTokenRateProvider_", type: "address" },
      { internalType: "address", name: "creditTokenRateProvider_", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AccessControlBadConfirmation", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "bytes32", name: "neededRole", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "AlreadySeeded", type: "error" },
  { inputs: [], name: "AmountInTooHigh", type: "error" },
  { inputs: [], name: "AmountOutTooLow", type: "error" },
  { inputs: [], name: "CurrentFeeOutOfNewBounds", type: "error" },
  { inputs: [], name: "DuplicateTokens", type: "error" },
  { inputs: [], name: "InsufficientFunds", type: "error" },
  { inputs: [], name: "InsufficientInitialDeposit", type: "error" },
  { inputs: [], name: "InvalidAsset", type: "error" },
  { inputs: [], name: "InvalidLiquidityProvider", type: "error" },
  { inputs: [], name: "InvalidOwner", type: "error" },
  { inputs: [], name: "InvalidPocket", type: "error" },
  { inputs: [], name: "InvalidRedeemRequest", type: "error" },
  { inputs: [], name: "InvalidRedeemer", type: "error" },
  { inputs: [], name: "InvalidSwap", type: "error" },
  { inputs: [], name: "InvalidSwapSizeBounds", type: "error" },
  { inputs: [], name: "InvalidThresholdBounds", type: "error" },
  { inputs: [], name: "InvalidToken", type: "error" },
  { inputs: [], name: "MaxFeeExceedsBps", type: "error" },
  { inputs: [], name: "MinFeeGreaterThanMaxFee", type: "error" },
  { inputs: [], name: "MinThresholdZero", type: "error" },
  { inputs: [], name: "NoNewShares", type: "error" },
  { inputs: [], name: "NotLiquidityProvider", type: "error" },
  { inputs: [], name: "Paused", type: "error" },
  { inputs: [], name: "PendingRedemptions", type: "error" },
  { inputs: [], name: "PrecisionTooHigh", type: "error" },
  { inputs: [], name: "PurchaseFeeOutOfBounds", type: "error" },
  { inputs: [], name: "RateProviderReturnsZero", type: "error" },
  { inputs: [], name: "RedeemerAlreadyAdded", type: "error" },
  { inputs: [], name: "RedemptionFeeOutOfBounds", type: "error" },
  { inputs: [], name: "RequestAlreadyExists", type: "error" },
  { inputs: [], name: "SameThreshold", type: "error" },
  { inputs: [], name: "StaleRate", type: "error" },
  { inputs: [], name: "SwapSizeExceeded", type: "error" },
  { inputs: [], name: "SwapSizeOutOfBounds", type: "error" },
  { inputs: [], name: "ThresholdOutOfBounds", type: "error" },
  { inputs: [], name: "ZeroAmount", type: "error" },
  { inputs: [], name: "ZeroAmountIn", type: "error" },
  { inputs: [], name: "ZeroAmountOut", type: "error" },
  { inputs: [], name: "ZeroRateProviderAddress", type: "error" },
  { inputs: [], name: "ZeroReceiver", type: "error" },
  { inputs: [], name: "ZeroTokenAddress", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "asset", type: "address" },
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "address", name: "receiver", type: "address" },
      { indexed: false, internalType: "uint256", name: "assetsDeposited", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "sharesMinted", type: "uint256" },
    ],
    name: "Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "pocket", type: "address" },
      { indexed: true, internalType: "address", name: "asset", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "DepositLiquidityFailed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "oldMinFee", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "oldMaxFee", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "newMinFee", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "newMaxFee", type: "uint256" },
    ],
    name: "FeeBoundsSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "oldFeeClaimer", type: "address" },
      { indexed: true, internalType: "address", name: "newFeeClaimer", type: "address" },
    ],
    name: "FeeClaimerSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "claimer", type: "address" },
      { indexed: false, internalType: "uint256", name: "shares", type: "uint256" },
    ],
    name: "FeeSharesAccrued",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "oldLowerBound", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "oldUpperBound", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "newLowerBound", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "newUpperBound", type: "uint256" },
    ],
    name: "MaxSwapSizeBoundsSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "oldMaxSwapSize", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "newMaxSwapSize", type: "uint256" },
    ],
    name: "MaxSwapSizeSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes4", name: "key", type: "bytes4" },
      { indexed: false, internalType: "bool", name: "paused", type: "bool" },
    ],
    name: "PausedSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "oldPocket", type: "address" },
      { indexed: true, internalType: "address", name: "newPocket", type: "address" },
      { indexed: false, internalType: "uint256", name: "amountTransferred", type: "uint256" },
    ],
    name: "PocketSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "oldPurchaseFee", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "newPurchaseFee", type: "uint256" },
    ],
    name: "PurchaseFeeSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "token", type: "address" },
      { indexed: true, internalType: "address", name: "oldRateProvider", type: "address" },
      { indexed: true, internalType: "address", name: "newRateProvider", type: "address" },
    ],
    name: "RateProviderSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "redeemer", type: "address" },
      { indexed: true, internalType: "address", name: "caller", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "RedeemCompleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "redeemer", type: "address" },
      { indexed: true, internalType: "address", name: "caller", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "RedeemInitiated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "oldRedemptionFee", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "newRedemptionFee", type: "uint256" },
    ],
    name: "RedemptionFeeSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "previousAdminRole", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "newAdminRole", type: "bytes32" },
    ],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      { indexed: true, internalType: "address", name: "account", type: "address" },
      { indexed: true, internalType: "address", name: "sender", type: "address" },
    ],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      { indexed: true, internalType: "address", name: "account", type: "address" },
      { indexed: true, internalType: "address", name: "sender", type: "address" },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "oldMinThreshold", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "oldMaxThreshold", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "newMinThreshold", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "newMaxThreshold", type: "uint256" },
    ],
    name: "StalenessThresholdBoundsSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "oldThreshold", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "newThreshold", type: "uint256" },
    ],
    name: "StalenessThresholdSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "assetIn", type: "address" },
      { indexed: true, internalType: "address", name: "assetOut", type: "address" },
      { indexed: false, internalType: "address", name: "sender", type: "address" },
      { indexed: true, internalType: "address", name: "receiver", type: "address" },
      { indexed: false, internalType: "uint256", name: "amountIn", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amountOut", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "referralCode", type: "uint256" },
    ],
    name: "Swap",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "redeemer", type: "address" }],
    name: "TokenRedeemerAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "redeemer", type: "address" }],
    name: "TokenRedeemerRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "asset", type: "address" },
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "address", name: "receiver", type: "address" },
      { indexed: false, internalType: "uint256", name: "assetsWithdrawn", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "sharesBurned", type: "uint256" },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [],
    name: "BPS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MANAGER_ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MANAGER_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OWNER_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAUSED_DEPOSIT_CREDIT",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAUSED_SWAP_COLLATERAL_TO_CREDIT",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAUSED_SWAP_CREDIT_TO_COLLATERAL",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAUSED_SWAP_CREDIT_TO_SWAP",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAUSED_SWAP_SWAP_TO_CREDIT",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAUSED_WITHDRAW_CREDIT",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAUSER_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REDEEMER_CONTRACT_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REDEEMER_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "redeemer", type: "address" }],
    name: "addTokenRedeemer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "calculatePurchaseFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "calculateRedemptionFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "collateralToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "collateralTokenRateProvider",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "redeemRequestId", type: "bytes32" }],
    name: "completeRedeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "numShares", type: "uint256" }],
    name: "convertToAssetValue",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "numShares", type: "uint256" },
    ],
    name: "convertToAssets",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "assets", type: "uint256" },
    ],
    name: "convertToShares",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "assetValue", type: "uint256" }],
    name: "convertToShares",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "creditToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "creditTokenRateProvider",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "assetsToDeposit", type: "uint256" },
    ],
    name: "deposit",
    outputs: [{ internalType: "uint256", name: "newShares", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "assetsToDeposit", type: "uint256" },
    ],
    name: "depositInitial",
    outputs: [{ internalType: "uint256", name: "newShares", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "feeClaimer",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bool", name: "roundUp", type: "bool" },
    ],
    name: "getAssetValue",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "redeemer", type: "address" },
      { internalType: "uint256", name: "creditTokenAmount", type: "uint256" },
    ],
    name: "initiateRedeem",
    outputs: [{ internalType: "bytes32", name: "redeemRequestId", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "liquidityProvider",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxStalenessThreshold",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxSwapSize",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxSwapSizeLowerBound",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxSwapSizeUpperBound",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minStalenessThreshold",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "pauseKey", type: "bytes4" }],
    name: "paused",
    outputs: [{ internalType: "bool", name: "isPaused", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingCreditTokenBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "redeemer", type: "address" }],
    name: "pendingRedemptions",
    outputs: [{ internalType: "uint256", name: "count", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pocket",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "assetsToDeposit", type: "uint256" },
    ],
    name: "previewDeposit",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "assetIn", type: "address" },
      { internalType: "address", name: "assetOut", type: "address" },
      { internalType: "uint256", name: "amountIn", type: "uint256" },
    ],
    name: "previewSwapExactIn",
    outputs: [{ internalType: "uint256", name: "amountOut", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "assetOut", type: "address" },
      { internalType: "uint256", name: "amountOut", type: "uint256" },
    ],
    name: "previewSwapExactInFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "assetIn", type: "address" },
      { internalType: "address", name: "assetOut", type: "address" },
      { internalType: "uint256", name: "amountOut", type: "uint256" },
    ],
    name: "previewSwapExactOut",
    outputs: [{ internalType: "uint256", name: "amountIn", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "assetOut", type: "address" },
      { internalType: "uint256", name: "amountOut", type: "uint256" },
    ],
    name: "previewSwapExactOutFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "maxAssetsToWithdraw", type: "uint256" },
    ],
    name: "previewWithdraw",
    outputs: [
      { internalType: "uint256", name: "sharesToBurn", type: "uint256" },
      { internalType: "uint256", name: "assetsWithdrawn", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "purchaseFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "requestId", type: "bytes32" }],
    name: "redeemRequests",
    outputs: [
      { internalType: "uint256", name: "blockNumber", type: "uint256" },
      { internalType: "address", name: "redeemer", type: "address" },
      { internalType: "uint256", name: "creditTokenAmount", type: "uint256" },
      { internalType: "uint256", name: "collateralTokenAmount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "redemptionFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "redeemer", type: "address" }],
    name: "removeTokenRedeemer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "callerConfirmation", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "newMinFee", type: "uint256" },
      { internalType: "uint256", name: "newMaxFee", type: "uint256" },
    ],
    name: "setFeeBounds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newFeeClaimer", type: "address" }],
    name: "setFeeClaimer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "newMaxSwapSize", type: "uint256" }],
    name: "setMaxSwapSize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "newLowerBound", type: "uint256" },
      { internalType: "uint256", name: "newUpperBound", type: "uint256" },
    ],
    name: "setMaxSwapSizeBounds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "key", type: "bytes4" }],
    name: "setPaused",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newPocket", type: "address" }],
    name: "setPocket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "newPurchaseFee", type: "uint256" }],
    name: "setPurchaseFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "address", name: "newRateProvider", type: "address" },
    ],
    name: "setRateProvider",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "newRedemptionFee", type: "uint256" }],
    name: "setRedemptionFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "newThreshold", type: "uint256" }],
    name: "setStalenessThreshold",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "newMinThreshold", type: "uint256" },
      { internalType: "uint256", name: "newMaxThreshold", type: "uint256" },
    ],
    name: "setStalenessThresholdBounds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "key", type: "bytes4" }],
    name: "setUnpaused",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "shares",
    outputs: [{ internalType: "uint256", name: "shares", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stalenessThreshold",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "assetIn", type: "address" },
      { internalType: "address", name: "assetOut", type: "address" },
      { internalType: "uint256", name: "amountIn", type: "uint256" },
      { internalType: "uint256", name: "minAmountOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "referralCode", type: "uint256" },
    ],
    name: "swapExactIn",
    outputs: [{ internalType: "uint256", name: "amountOut", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "assetIn", type: "address" },
      { internalType: "address", name: "assetOut", type: "address" },
      { internalType: "uint256", name: "amountOut", type: "uint256" },
      { internalType: "uint256", name: "maxAmountIn", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "referralCode", type: "uint256" },
    ],
    name: "swapExactOut",
    outputs: [{ internalType: "uint256", name: "amountIn", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "swapToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "swapTokenRateProvider",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalAssets",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalShares",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "maxAssetsToWithdraw", type: "uint256" },
    ],
    name: "withdraw",
    outputs: [{ internalType: "uint256", name: "assetsWithdrawn", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const satisfies Abi;
